apiVersion: v1
kind: Service
metadata:
  name: project-detail-db-service
spec:
  selector:
    app: project-detail-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer