apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-api-deployment
  labels:
    app: discount-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discount-api
  template:
    metadata:
      labels:
        app: discount-api
    spec:
      containers:
        - name: discount-api
          image:  netcoremicroservicesacr.azurecr.io/discountapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: discount-db-configmap
                    key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: discount-api-service
spec:
  type: LoadBalancer
  selector:
    app: discount-api
  ports:
    - protocol: TCP
      port: 80