apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcoremicroservices-api-gateway-deployment
  labels:
    app: netcoremicroservicesapigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcoremicroservicesapigateway
  template:
    metadata:
      labels:
        app: netcoremicroservicesapigateway
    spec:
      containers:
        - name: netcoremicroservicesapigateway
          image:  netcoremicroservicesacr.azurecr.io/netcoremicroservicesapigateway:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: netcoremicroservicesapigatewayservice
spec:
  type: LoadBalancer
  selector:
    app: netcoremicroservicesapigateway
  ports:
    - protocol: TCP
      port: 80