version: '3.4'

services:
  netcoremicroservices.api:
    image: ${DOCKER_REGISTRY-}netcoremicroservicesapi
    build:
      context: .
      dockerfile: NetCoreMicroservices.API/Dockerfile

  netcoremicroservices.client:
    image: ${DOCKER_REGISTRY-}netcoremicroservicesclient
    build:
      context: .
      dockerfile: NetCoreMicroservices.Client/Dockerfile

  discount.db:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: NetCoreMicroservices.DiscountGrpc/Discount.Grpc/Dockerfile
 
  netcoremicroservices.db:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  webapi-gw:
    image: ${DOCKER_REGISTRY-}webapigw
    build:
      context: .
      dockerfile: WebAPI-GW/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.API/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:

