version: '3.4'

services:
  basketdb:
    image: redis
  discount.db:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  mongo.db:
    image: mongo

  gamecatalog.db:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  web.mvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: src/webapps/Web.Mvc/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/services/Catalog/Catalog.API/Dockerfile
      args:
        - NUGET_PAT

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/services/Basket/Basket.API/Dockerfile

  webapi-gw:
    image: ${DOCKER_REGISTRY-}webapigw
    build:
      context: .
      dockerfile: src/services/API-Gws/WebAPI-GW/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/services/Discount/Discount.Grpc/Dockerfile
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: src/services/Discount/Discount.API/Dockerfile

  gamecatalog.api:
    image: ${DOCKER_REGISTRY-}gamecatalogapi
    build:
      context: .
      dockerfile: src/services/GameCatalog/GameCatalog.API/Dockerfile
      args:
        - NUGET_PAT

  signalr.api:
    image: ${DOCKER_REGISTRY-}signalrapi
    build:
      context: .
      dockerfile: src/services/SignalR.API/Dockerfile

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: src/services/Inventory/Inventory.API/Dockerfile

  web.spa:
    image: ${DOCKER_REGISTRY-}webspa
    build:
      context: .
      dockerfile: src/webapps/Web.Spa/Dockerfile


  realtimetransmission.api:
    image: ${DOCKER_REGISTRY-}realtimetransmissionapi
    build:
      context: .
      dockerfile: src/services/RealTimeTransmission/RealTimeTransmission.API/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:

   





















