version: '3.4'

services:
  netcoremicroservices.api:
    image: ${DOCKER_REGISTRY-}netcoremicroservicesapi
    build:
      context: .
      dockerfile: NetCoreMicroservices.API/Dockerfile

  netcoremicroservices.client:
    image: ${DOCKER_REGISTRY-}netcoremicroservicesclient
    build:
      context: .
      dockerfile: NetCoreMicroservices.Client/Dockerfile
  netcoremicroservices.db:
    image: mongo

  netcoremicroservices.apigateway:
    image: ${DOCKER_REGISTRY-}netcoremicroservicesapigateway
    build:
      context: .
      dockerfile: NetCoreMicroservices.APIGateway/Dockerfile


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

