version: '3.4'

services:
  basketdb:
    image: redis
  discount.db:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  mongo.db:
    image: mongo

  gamecatalog.db:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  web.spa:
    image: ${DOCKER_REGISTRY-}webspa
    build:
      context: .
      dockerfile: src/webapps/Web.Spa/Dockerfile


volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:


   


















