version: '3.4'

services:

  netcoremicroservices.db:
    container_name: netmicroservicesmongo
    restart: always
    ports:
      - 27017:27017  
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db

  discount.db:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=duch
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 


  netcoremicroservices.api:
    container_name: netcoremicroservicesapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://netmicroservicesmongo:27017"
    depends_on:
      - netcoremicroservices.db
    ports:
      - "8000:80"

  netcoremicroservices.client:
    container_name: netcoremicroservicesclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "NetCoreMicroservicesAPIUrl=http://catalogapi"
    depends_on:
      - netcoremicroservices.db
      - netcoremicroservices.api
    ports:
      - "8001:80"

  webapi-gw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8081:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:80"

  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://netmicroservicesmongo:27017"
    ports:
      - "8083:80"


  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"



