version: '3.4'

services:
  netcoremicroservices.db:
    container_name: netmicroservicesmongo
    restart: always
    ports:
      - 27017:27017  
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db

  basketdb:
    container_name: basketdb
    restart: always    
    ports:
        - "6379:6379"

  discount.db:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=duch
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@patrikduch.com
      - PGADMIN_DEFAULT_PASSWORD=duch
    restart: always
    ports:
      -  "5050:80"
    volumes:
      -  pgadmin_data:/root/.pgadmnin 

  basket.api:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
    depends_on:
        - basketdb
    ports:
      - "8080:80"

  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__DatabaseName=ProductDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__ConnectionString=mongodb://netmicroservicesmongo:27017"
    ports:
      - "8081:80"

  discount.api:
    container_name: discountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=duch;"
    ports:
      - "8082:80"
    depends_on:
    - discount.db

  webapi-gw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8083:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8084:80"
      - "1000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
