apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalogapi
          image:  netcoremicroservicesacr.azurecr.io/catalogapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development

            - name: DatabaseSettings__DatabaseName
              valueFrom:
                  secretKeyRef:
                    name: catalog-db-secret
                    key: Host
                    
            - name: DatabaseSettings__CollectionName
              valueFrom:
                  secretKeyRef:
                    name: catalog-db-secret
                    key: CollectionName

            - name: DatabaseSettings__Username
              valueFrom:
                  secretKeyRef:
                    name: catalog-db-secret
                    key: Username

            - name: DatabaseSettings__Port
              valueFrom:
                  secretKeyRef:
                    name: catalog-db-secret
                    key: Port

            - name: DatabaseSettings__ServiceName
              valueFrom:
                  secretKeyRef:
                    name: catalog-db-secret
                    key: ServiceName

      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
spec:
  type: LoadBalancer
  selector:
    app: catalog-api
  ports:
    - protocol: TCP
      port: 80