# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
    branches:
      include:
      - master
    paths:
      include:
      - src/services/Basket/Basket.API/*
      - deployment/aks/services/basket/basket-api/basket-api.yaml

resources:
- repo: self

variables:
  dockerfilePath: 'src/services/Basket/Basket.API/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stagecontainerRegistry
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(ACR_IMAGE_REPOSITORY)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(DOCKER_REGISTRY_CONNECTION)
        buildContext: $(Build.SourcesDirectory)/
        tags: |
          $(tag)

    - upload: deployment/aks
      artifact: aks

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'patrikduchnetcoremicroservices.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(ACR_IMAGE_PULL_SECRET)
              dockerRegistryEndpoint: $(DOCKER_REGISTRY_CONNECTION)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/aks/services/basket/basket-api/basket-api.yaml
              imagePullSecrets: |
                $(ACR_IMAGE_PULL_SECRET)
              containers: |
                $(ACR_CONTAINER_NAME)/$(ACR_IMAGE_REPOSITORY):$(tag)

