# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
    branches:
      include:
      - master
    paths:
      include:
      - src/services/Basket/Basket.API/*
      - deployment/aks/services/basket/basket-api/basket-api.yaml

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '8c099962-5c7d-4d2b-9587-c8e042484598'
  containerRegistry: 'netcoremicroservicesacr.azurecr.io'
  dockerfilePath: 'src/services/Basket/Basket.API/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'netcoremicroservicesacr1748cec4-auth'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: Build stagecontainerRegistry
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      env:
        IMAGE_REPOSITORY: $(ACR_IMAGE_REPOSITORY)
        CONTAINER_NAME: $(ACR_CONTAINER_NAME)

      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)/
        tags: |
          $(tag)

    - upload: deployment/aks
      artifact: aks

