apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
  labels:
    app: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: productapi
          image:  netcoremicroservicesacr.azurecr.io/productapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  secretKeyRef:
                    name: product-api-secret
                    key: ConnectionString

      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: product-api-service
spec:
  type: ClusterIP
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 80