apiVersion: v1
kind: Service
metadata:
  name: product-db-service  # Reference name that can be used for intercommunication
spec:
  type: LoadBalancer
  selector:
    component: product-db
  ports:
    - port: 5432
      targetPort: 5432