apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service  # Reference name that can be used for intercommunication
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432