kind: PersistentVolume
apiVersion: v1
metadata:
  name: discount-db-pv-volume
  labels:
    type: local
    app: discount-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: discount-db-pv-claim
  labels:
    app: discount-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi