apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-spa-deployment
  labels:
    app: web-spa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-spa
  template:
    metadata:
      labels:
        app: web-spa
    spec:
      containers:
        - name: webspa
          image:  netcoremicroservicesacr.azurecr.io/webspa:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-spa-service
spec:
  type: LoadBalancer
  selector:
    app: web-spa
  ports:
    - protocol: TCP
      port: 80