# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
    branches:
      include:
      - master
    paths:
      include:
      - src/services/GameCatalog/GameCatalog.API/*
      - deployment/aks/services/game-catalog/game-catalog-api/game-catalog-api.yaml

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '8454a2ba-d7b1-4962-8832-922f293b96db'
  imageRepository: 'gamecatalogapi'
  containerRegistry: 'netcoremicroservicesacr.azurecr.io'
  dockerfilePath: 'src/services/GameCatalog/GameCatalog.API/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'netcoremicroservicesacr1748cec4-auth'
  pipelineName: game-catalog-api

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore Nuget Packages'
      inputs:
        command: 'restore'
        projects: '**/GameCatalog.API.csproj'
        
    - task: DotNetCoreCLI@2
      displayName: 'Build GameCatalog.API '
      inputs:
        command: 'build'
        projects: '**/GameCatalog.API.csproj'
        arguments: '--no-restore'
      
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)/
        tags: |
          $(tag)
    - upload: deployment/aks
      artifact: aks

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'patrikduchnetcoremicroservices.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/aks/services/game-catalog/game-catalog-api/game-catalog-api.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)