apiVersion: v1
kind: Service
metadata:
  name: postgres-example-db-service  # Reference name that can be used for intercommunication
spec:
  type: LoadBalancer
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432