apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcoremicroservicessapi-deployment
  labels:
    app: netcoremicroservicessapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcoremicroservicessapi
  template:
    metadata:
      labels:
        app: netcoremicroservicessapi
    spec:
      containers:
        - name: netcoremicroservicessapi
          image: patrikduch/netmicroservices.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: netcoremicroservicessapi-service
spec:
  type: NodePort
  selector:
    app: netcoremicroservicessapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 31000