apiVersion: v1
kind: Service
metadata:
  name: user-db-service  # Reference name that can be used for intercommunication
spec:
  type: LoadBalancer
  selector:
    component: user-db
  ports:
    - port: 5432
      targetPort: 5432