apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user-db
  template:
    metadata:
      labels:
        component: user-db
    spec:
      volumes:
        - name: user-db-storage
          persistentVolumeClaim:
            claimName: user-db-pv-claim
      containers:
        - name: postgres
          image: postgres:10.3
          ports:
            - containerPort: 5432
          #volumeMounts:
          #  - name: user-db-storage
          #    mountPath:  /var/lib/postgresql/data
          #    subPath: postgres

          volumeMounts:
            - mountPath: /var/lib/postgresql/
              subPath: data
              name: userdb-storage


          env:            
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                    name: user-db-secret
                    key: PGUSERNAME

            - name: POSTGRES_DB
              valueFrom: 
                secretKeyRef:
                    name: user-db-secret
                    key: PGDBNAME

            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                    name: user-db-secret
                    key: PGPASSWORD
      volumes:
      - name: userdb-storage
        persistentVolumeClaim:
          claimName: user-db-pv-claim
