apiVersion: v1
kind: Service
metadata:
  name: discount-postgresdb-service  # Reference name that can be used for intercommunication
spec:
  type: ClusterIP
  selector:
    component: discount-postgresdb
  ports:
    - port: 5432
      targetPort: 5432