
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
      - src/nugets/MongoDbWrapper.Nuget/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'NetMicroservices.Common'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'
      externalFeedCredentials: 'NetMicroservices.Common'


- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'src/nugets/MongoDbWrapper.Nuget/*.csproj'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'src/nugets/MongoDbWrapper.Nuget/*.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'netmicroservices/NetMicroservices.Common'
    versioningScheme: 'off'
    allowPackageConflicts: true