
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
      - src/nugets/NetMicroservices.Configuration/NetMicroservices.Configuration.Nuget/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'src/nugets/NetMicroservices.Configuration/NetMicroservices.Configuration.Nuget/*.csproj'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'src/nugets/NetMicroservices.Configuration/NetMicroservices.Configuration.Nuget/*.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'netmicroservices/NetMicroservices.Dbs'
    versioningScheme: 'off'
    allowPackageConflicts: true